import { BarChart3, TrendingUp } from "lucide-react";

import {
    DashboardLayout,
    ProgressCard,
    QuizAnalyticsCard,
} from "../../../components/dashboard";
import ComingSoonCard from "../../../components/dashboard/ComingSoonCard";
import { StatsProvider } from "@/features/stats/StatsContext";
import StatsFilterBar from "@/components/stats/StatsFilterBar";
import WeeklyMonthlySummary from "@/components/stats/WeeklyMonthlySummary";
import XpProgressChart from "@/components/stats/XpProgressChart";
import PracticeTimeChart from "@/components/stats/PracticeTimeChart";
import ConversationSessionsChart from "@/components/stats/ConversationSessionsChart";
import CategoryDistributionChart from "@/components/stats/CategoryDistributionChart";
import TimeHeatmap from "@/components/stats/TimeHeatmap";

export default function StatsPage() {
    return (
        <DashboardLayout>
            <StatsProvider>
                <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white shadow-2xl shadow-slate-900/20 sm:p-8">
                    <div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-blue-500/30 blur-3xl" aria-hidden="true" />
                    <div className="absolute -bottom-24 left-1/3 h-72 w-72 rounded-full bg-pink-400/20 blur-3xl" aria-hidden="true" />

                    <div className="relative space-y-5">
                        <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.18em] text-blue-100">
                            <BarChart3 className="h-4 w-4" aria-hidden="true" />
                            Statistics
                        </div>
                        <div className="space-y-3">
                            <h1 className="max-w-2xl text-4xl font-bold tracking-[-0.04em] sm:text-5xl">Track your speaking progress.</h1>
                            <p className="max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">See streaks, practice minutes, weekly activity, skill scores, and lesson assessment results as they are generated by your learning journey.</p>
                        </div>
                    </div>
                </section>

                {/* Date-range filter — every chart below reads from this. */}
                <StatsFilterBar />

                {/* Weekly & Monthly Progress — the same summary re-rendered under
                    whichever range is selected (7d/30d cover "weekly"/"monthly"),
                    not a separate feature. */}
                <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                    <p className="text-sm font-bold text-slate-500">Overview</p>
                    <div className="mt-5">
                        <WeeklyMonthlySummary />
                    </div>
                </section>

                <div className="grid gap-6 lg:grid-cols-2">
                    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                        <div className="mb-5 flex items-center justify-between">
                            <div>
                                <p className="text-sm font-bold text-slate-500">Weekly activity</p>
                                <h2 className="mt-1 text-xl font-bold tracking-[-0.03em] text-slate-900">Practice minutes</h2>
                            </div>
                            <TrendingUp className="h-6 w-6 text-emerald-600" aria-hidden="true" />
                        </div>
                        <PracticeTimeChart />
                    </section>

                    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                        <div className="mb-5 flex items-center justify-between">
                            <div>
                                <p className="text-sm font-bold text-slate-500">XP progress</p>
                                <h2 className="mt-1 text-xl font-bold tracking-[-0.03em] text-slate-900">XP earned over time</h2>
                            </div>
                            <BarChart3 className="h-6 w-6 text-blue-600" aria-hidden="true" />
                        </div>
                        <XpProgressChart />
                    </section>
                </div>

                <div className="grid gap-6 lg:grid-cols-2">
                    <ProgressCard />

                    <ComingSoonCard
                        title="Speaking Trend Analytics"
                        description="Fluency, pronunciation and confidence trends will appear here once real-time speech scoring lands in a future phase."
                    />
                </div>

                <div className="grid gap-6 lg:grid-cols-2">
                    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                        <div className="mb-5 flex items-center justify-between">
                            <div>
                                <p className="text-sm font-bold text-slate-500">Sessions</p>
                                <h2 className="mt-1 text-xl font-bold tracking-[-0.03em] text-slate-900">Conversation sessions</h2>
                            </div>
                        </div>
                        <ConversationSessionsChart />
                    </section>

                    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                        <div className="mb-5 flex items-center justify-between">
                            <div>
                                <p className="text-sm font-bold text-slate-500">Distribution</p>
                                <h2 className="mt-1 text-xl font-bold tracking-[-0.03em] text-slate-900">Practice category distribution</h2>
                            </div>
                        </div>
                        <CategoryDistributionChart />
                    </section>
                </div>

                <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                    <div className="mb-5 flex items-center justify-between">
                        <div>
                            <p className="text-sm font-bold text-slate-500">Time-based learning</p>
                            <h2 className="mt-1 text-xl font-bold tracking-[-0.03em] text-slate-900">Daily activity heatmap</h2>
                        </div>
                    </div>
                    <TimeHeatmap />
                </section>

                {/* Phase 11 — Quiz assessment analytics (now includes a Module M12
                    score trend line, filtered by the shared range above). */}
                <QuizAnalyticsCard />

                <div className="grid gap-6 lg:grid-cols-2">
                    <ComingSoonCard
                        title="Vocabulary Growth"
                        description="New words learned, mastery tracking and growth trends will appear here once vocabulary tracking is built."
                    />
                    <ComingSoonCard
                        title="Grammar Improvement Analytics"
                        description="Grammar accuracy over time and common mistake patterns will appear here once grammar analysis is built."
                    />
                </div>
            </StatsProvider>
        </DashboardLayout>
    );
}
